tests: make the hid-decode test a bit easier to follow
Instead of nested classes with magic attributes on self, let's split
this out to make more use of fixtures so it's easier to follow what each
individual test does.

Testing performed should be identical to the one before with one
exception: the uhid device previously had all the tests (e.g. test_read)
of the base class. But the uhid device just gives us the same output
anyway, there's no real need to do those so skipping them is fine.

Part-of: <https://gitlab.freedesktop.org/libevdev/hid-tools/-/merge_requests/176>